name: dbtest
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  
  flutter:
    sdk: flutter
  path: ^1.8.0

